"""Deterministic provider for tests and for running the app without an API key.

The receipt "extraction" returns a plausible draft; the query planner uses a
few keyword heuristics so the natural-language feature is usable in demos.
"""

from __future__ import annotations

import calendar
import re
from datetime import date, timedelta

from app.ai.base import (
    AIUsage,
    ExtractionContext,
    ExtractionResult,
    QueryPlanResult,
)
from app.ai.schemas import ExtractedLineItem, QueryIntent, QueryPlan, ReceiptExtraction

_MONTHS = {name.lower(): i for i, name in enumerate(calendar.month_name) if name}
_MONTHS.update(
    {
        "januar": 1, "februar": 2, "märz": 3, "maerz": 3, "april": 4, "mai": 5, "juni": 6,
        "juli": 7, "august": 8, "september": 9, "oktober": 10, "november": 11, "dezember": 12,
    }
)  # fmt: skip


class MockProvider:
    name = "mock"
    model = "mock-v1"

    def _usage(self) -> AIUsage:
        return AIUsage(provider=self.name, model=self.model, input_tokens=0, output_tokens=0)

    def extract_receipt(
        self, data: bytes, media_type: str, context: ExtractionContext
    ) -> ExtractionResult:
        category = context.categories[0] if context.categories else None
        merchant = "Demo Store"
        if context.hints:
            merchant = context.hints[0].merchant
            category = context.hints[0].category
        extraction = ReceiptExtraction(
            merchant=merchant,
            date=date.today().isoformat(),
            total_amount=round(10 + (len(data) % 9000) / 100, 2),
            currency=context.default_currency,
            vat_rate=19.0,
            vat_amount=None,
            category=category,
            description="Demo extraction (mock AI provider - no API key configured)",
            line_items=[ExtractedLineItem(description="Sample item", quantity=1, total=None)],
            confidence=0.5,
            notes="Generated by the mock provider. Set AI_PROVIDER=anthropic for real extraction.",
        )
        return ExtractionResult(extraction=extraction, usage=self._usage())

    def plan_query(self, question: str, categories: list[str], today: date) -> QueryPlanResult:
        q = question.lower()
        intent: QueryIntent = "sum"
        # Group intents first: "show spending by category" is a breakdown, not a list.
        if re.search(r"\b(per category|by category|pro kategorie|nach kategorie)\b", q):
            intent = "by_category"
        elif re.search(r"\b(per month|by month|pro monat|monatlich|trend)\b", q):
            intent = "by_month"
        elif re.search(r"\b(where|wo|top|most|meiste)\b", q):
            intent = "top_merchants"
        elif re.search(r"\b(how many|wie viele|anzahl|count)\b", q):
            intent = "count"
        elif re.search(r"\b(average|durchschnitt|im schnitt)\b", q):
            intent = "average"
        elif re.search(r"\b(list|zeig|show|welche)\b", q):
            intent = "list"

        date_from: date | None = None
        date_to: date | None = None
        if re.search(r"\b(last month|letzten monat|letzter monat|vormonat)\b", q):
            first_this = today.replace(day=1)
            date_to = first_this - timedelta(days=1)
            date_from = date_to.replace(day=1)
        elif re.search(r"\b(this month|diesen monat|dieser monat)\b", q):
            date_from = today.replace(day=1)
            date_to = today
        elif re.search(r"\b(this year|dieses jahr)\b", q):
            date_from = today.replace(month=1, day=1)
            date_to = today
        else:
            for name, month in _MONTHS.items():
                if re.search(rf"\b{name}\b", q):
                    year = today.year if month <= today.month else today.year - 1
                    date_from = date(year, month, 1)
                    date_to = date(year, month, calendar.monthrange(year, month)[1])
                    break

        matched = [c for c in categories if c.lower() in q or c.split(" ")[0].lower() in q]
        plan = QueryPlan(
            intent=intent,
            date_from=date_from.isoformat() if date_from else None,
            date_to=date_to.isoformat() if date_to else None,
            categories=matched,
            merchant_contains=None,
            min_amount=None,
            max_amount=None,
            limit=10,
            explanation="Interpreted with keyword heuristics (mock AI provider).",
        )
        return QueryPlanResult(plan=plan, usage=self._usage())
