"""Local filesystem storage for uploaded receipts.

Files are stored under `<upload_dir>/<user_id>/<uuid>.<ext>` - the name is
generated by the server, never taken from the client, so path traversal is
impossible. An S3-compatible backend can implement the same three methods.
"""

from __future__ import annotations

import uuid
from pathlib import Path

EXTENSIONS = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
    "application/pdf": "pdf",
}


class LocalStorage:
    def __init__(self, base_dir: Path) -> None:
        self.base_dir = base_dir.resolve()
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def _resolve(self, relative_path: str) -> Path:
        path = (self.base_dir / relative_path).resolve()
        if self.base_dir not in path.parents:
            raise ValueError("Invalid storage path")
        return path

    def save(self, user_id: str, media_type: str, data: bytes) -> str:
        ext = EXTENSIONS[media_type]
        relative = f"{user_id}/{uuid.uuid4()}.{ext}"
        path = self._resolve(relative)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return relative

    def read(self, relative_path: str) -> bytes:
        return self._resolve(relative_path).read_bytes()

    def delete(self, relative_path: str) -> None:
        path = self._resolve(relative_path)
        if path.exists():
            path.unlink()

    def delete_user_files(self, user_id: str) -> None:
        user_dir = self._resolve(user_id)
        if user_dir.exists():
            for file in user_dir.iterdir():
                file.unlink()
            user_dir.rmdir()
